package com.consulate.dao;
// Generated Jan 30, 2018 7:31:23 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attestation generated by hbm2java
 */
@Entity
@Table(name = "attestation", catalog = "consular")
public class Attestation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -555390943358765915L;
	private Integer idattestation;
	private AttestationType attestationType;
	private Person person;
	private User user;
	private int createdDate;
	private String content;

	public Attestation() {
	}

	public Attestation(AttestationType attestationType, Person person, User user, int createdDate, String content) {
		this.attestationType = attestationType;
		this.person = person;
		this.user = user;
		this.createdDate = createdDate;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idattestation", unique = true, nullable = false)
	public Integer getIdattestation() {
		return this.idattestation;
	}

	public void setIdattestation(Integer idattestation) {
		this.idattestation = idattestation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attestation_type", nullable = false)
	public AttestationType getAttestationType() {
		return this.attestationType;
	}

	public void setAttestationType(AttestationType attestationType) {
		this.attestationType = attestationType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "createdDate", nullable = false)
	public int getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(int createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
