package com.consulate.dao;
// Generated Jan 30, 2018 7:31:23 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AttestationType generated by hbm2java
 */
@Entity
@Table(name = "attestation_type", catalog = "consular")
public class AttestationType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6200280709479940265L;
	private Integer idattestationType;
	private String type;
	private Set<Attestation> attestations = new HashSet<Attestation>(0);

	public AttestationType() {
	}

	public AttestationType(String type) {
		this.type = type;
	}

	public AttestationType(String type, Set attestations) {
		this.type = type;
		this.attestations = attestations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idattestation_type", unique = true, nullable = false)
	public Integer getIdattestationType() {
		return this.idattestationType;
	}

	public void setIdattestationType(Integer idattestationType) {
		this.idattestationType = idattestationType;
	}

	@Column(name = "type", nullable = false, length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attestationType")
	public Set<Attestation> getAttestations() {
		return this.attestations;
	}

	public void setAttestations(Set<Attestation> attestations) {
		this.attestations = attestations;
	}

}
