package com.consulate.dao;
// Generated Jan 30, 2018 7:31:23 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Consulate generated by hbm2java
 */
@Entity
@Table(name = "consulate", catalog = "consular")
public class Consulate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5533980332910981147L;
	private Integer idconsulat;
	private Country country;
	private String name;
	private String longName;
	private Set<Person> persons = new HashSet<Person>(0);
	private Set<User> users = new HashSet<User>(0);

	public Consulate() {
	}

	public Consulate(Country country, String name) {
		this.country = country;
		this.name = name;
	}

	public Consulate(Country country, String name, String longName, Set persons, Set users) {
		this.country = country;
		this.name = name;
		this.longName = longName;
		this.persons = persons;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idconsulat", unique = true, nullable = false)
	public Integer getIdconsulat() {
		return this.idconsulat;
	}

	public void setIdconsulat(Integer idconsulat) {
		this.idconsulat = idconsulat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "longName", length = 45)
	public String getLongName() {
		return this.longName;
	}

	public void setLongName(String longName) {
		this.longName = longName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consulate")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consulate")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
