package com.consulate.dao;
// Generated Jan 30, 2018 7:31:23 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "consular")
public class Country implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1891269414540554496L;
	private Integer idcountry;
	private String name;
	private String longName;
	private String continent;
	private Set<Consulate> consulates = new HashSet<Consulate>(0);

	public Country() {
	}

	public Country(String name) {
		this.name = name;
	}

	public Country(String name, String longName, String continent, Set consulates) {
		this.name = name;
		this.longName = longName;
		this.continent = continent;
		this.consulates = consulates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcountry", unique = true, nullable = false)
	public Integer getIdcountry() {
		return this.idcountry;
	}

	public void setIdcountry(Integer idcountry) {
		this.idcountry = idcountry;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "longName", length = 45)
	public String getLongName() {
		return this.longName;
	}

	public void setLongName(String longName) {
		this.longName = longName;
	}

	@Column(name = "continent", length = 45)
	public String getContinent() {
		return this.continent;
	}

	public void setContinent(String continent) {
		this.continent = continent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<Consulate> getConsulates() {
		return this.consulates;
	}

	public void setConsulates(Set<Consulate> consulates) {
		this.consulates = consulates;
	}

	public static void main(String[] args) {
		System.out.println("hello");
	}
}
