package com.consulate.dao;
// Generated Jan 30, 2018 7:31:23 PM by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "consular")
public class Person implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7876052249213977860L;
	private Integer idperson;
	private Consulate consulate;
	private String name;
	private String lastName;
	private Date birthdate;
	private String cnie;
	private String ic;
	private Set<Attestation> attestations = new HashSet<Attestation>(0);

	public Person() {
	}

	public Person(Consulate consulate, String name, String lastName, String cnie, String ic) {
		this.consulate = consulate;
		this.name = name;
		this.lastName = lastName;
		this.cnie = cnie;
		this.ic = ic;
	}

	public Person(Consulate consulate, String name, String lastName, Date birthdate, String cnie, String ic,
			Set<Attestation> attestations) {
		this.consulate = consulate;
		this.name = name;
		this.lastName = lastName;
		this.birthdate = birthdate;
		this.cnie = cnie;
		this.ic = ic;
		this.attestations = attestations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idperson", unique = true, nullable = false)
	public Integer getIdperson() {
		return this.idperson;
	}

	public void setIdperson(Integer idperson) {
		this.idperson = idperson;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consulate", nullable = false)
	public Consulate getConsulate() {
		return this.consulate;
	}

	public void setConsulate(Consulate consulate) {
		this.consulate = consulate;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "lastName", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdate", length = 10)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "cnie", nullable = false, length = 45)
	public String getCnie() {
		return this.cnie;
	}

	public void setCnie(String cnie) {
		this.cnie = cnie;
	}

	@Column(name = "ic", nullable = false, length = 45)
	public String getIc() {
		return this.ic;
	}

	public void setIc(String ic) {
		this.ic = ic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Attestation> getAttestations() {
		return this.attestations;
	}

	public void setAttestations(Set<Attestation> attestations) {
		this.attestations = attestations;
	}

}
