package com.consulate.dao;
// Generated Jan 30, 2018 7:31:23 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "consular")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2675226554119175322L;
	private Integer iduser;
	private Consulate consulate;
	private String username;
	private String password;
	private int createdDate;
	private Set<Attestation> attestations = new HashSet<Attestation>(0);
	private Set<Role> roles = new HashSet<Role>(0);

	public User() {
	}

	public User(Consulate consulate, String username, String password, int createdDate) {
		this.consulate = consulate;
		this.username = username;
		this.password = password;
		this.createdDate = createdDate;
	}

	public User(Consulate consulate, String username, String password, int createdDate, Set attestations, Set roles) {
		this.consulate = consulate;
		this.username = username;
		this.password = password;
		this.createdDate = createdDate;
		this.attestations = attestations;
		this.roles = roles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iduser", unique = true, nullable = false)
	public Integer getIduser() {
		return this.iduser;
	}

	public void setIduser(Integer iduser) {
		this.iduser = iduser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "consulate", nullable = false)
	public Consulate getConsulate() {
		return this.consulate;
	}

	public void setConsulate(Consulate consulate) {
		this.consulate = consulate;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "createdDate", nullable = false)
	public int getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(int createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Attestation> getAttestations() {
		return this.attestations;
	}

	public void setAttestations(Set<Attestation> attestations) {
		this.attestations = attestations;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_has_role", catalog = "consular", joinColumns = {
			@JoinColumn(name = "iduser", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_idrole", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
